listoflinuxapp:
  - name: firstlinuxapp    
    os_type: Linux
    sku_name: P1v2

listofwinapp:
  - name: firstwindowapp
    os_type: "Windows"
    sku_name: "P1v2"

listofstorage:
  - name: storageaccount
    account_tier: "Standard"
    account_replication_type: "GRS"

listofsqlserver:
  - name: myexamplesqlserver
    version: "12.0"

listofwafpolicies:
  - name: wafpolicy
    managed_rules:
      managed_rule_set:
        version: "3.2"
        rule_group_override:
          rule_group_name: "REQUEST-920-PROTOCOL-ENFORCEMENT"
          rule:
            id: "920440"
            enabled: true
            action: "Block"
