listoflinuxapp:
  - name: firstlinuxapp    
    os_type: Linux
    sku_name: P1v2

listofwinapp:
  - name: firstwindowapp
    os_type: "Windows"
    sku_name: "P1v2"

listofstorage:
  - name: storageaccount
    account_tier: "Standard"
    account_replication_type: "GRS"

listofsqlserver:
  - name: myexamplesqlserver
    version: 12.0
    administrator_login: "4dm1n157r470r"
    administrator_login_password: "4-v3ry-53cr37-p455w0rd"